use super::Command;

pub const COMMANDS: &[Command] = &[
    // File
    Command {
        group: "file",
        name: "New",
        hint: "Ctrl+N",
        run: super::cmd_new,
    },
    Command {
        group: "file",
        name: "Open…",
        hint: "Ctrl+O",
        run: super::cmd_open,
    },
    Command {
        group: "file",
        name: "Save",
        hint: "Ctrl+S",
        run: super::cmd_save,
    },
    Command {
        group: "file",
        name: "Save As…",
        hint: "Ctrl+Shift+S",
        run: super::cmd_save_as,
    },
    // Edit
    Command {
        group: "edit",
        name: "Undo",
        hint: "Ctrl+Z",
        run: super::cmd_undo,
    },
    Command {
        group: "edit",
        name: "Redo",
        hint: "Ctrl+Shift+Z",
        run: super::cmd_redo,
    },
    Command {
        group: "edit",
        name: "Delete current block",
        hint: "",
        run: super::cmd_delete_block,
    },
    Command {
        group: "edit",
        name: "Clear inline style",
        hint: "",
        run: super::cmd_clear_style,
    },
    // Format toggles (set the pending style applied to next typed characters)
    Command {
        group: "fmt",
        name: "Toggle bold",
        hint: "Ctrl+B",
        run: super::cmd_toggle_bold,
    },
    Command {
        group: "fmt",
        name: "Toggle italic",
        hint: "Ctrl+I",
        run: super::cmd_toggle_italic,
    },
    Command {
        group: "fmt",
        name: "Toggle underline",
        hint: "Ctrl+U",
        run: super::cmd_toggle_underline,
    },
    Command {
        group: "fmt",
        name: "Toggle strikethrough",
        hint: "",
        run: super::cmd_toggle_strike,
    },
    Command {
        group: "fmt",
        name: "Toggle inline code",
        hint: "",
        run: super::cmd_toggle_code,
    },
    // Insert (new block after current)
    Command {
        group: "insert",
        name: "Heading 1",
        hint: "",
        run: super::cmd_h1,
    },
    Command {
        group: "insert",
        name: "Heading 2",
        hint: "",
        run: super::cmd_h2,
    },
    Command {
        group: "insert",
        name: "Heading 3",
        hint: "",
        run: super::cmd_h3,
    },
    Command {
        group: "insert",
        name: "Heading 4",
        hint: "",
        run: super::cmd_h4,
    },
    Command {
        group: "insert",
        name: "Paragraph",
        hint: "",
        run: super::cmd_p,
    },
    Command {
        group: "insert",
        name: "Blockquote",
        hint: "",
        run: super::cmd_blockquote,
    },
    Command {
        group: "insert",
        name: "Bullet list item",
        hint: "",
        run: super::cmd_bullet,
    },
    Command {
        group: "insert",
        name: "Numbered list item",
        hint: "",
        run: super::cmd_numbered,
    },
    Command {
        group: "insert",
        name: "Preformatted block",
        hint: "",
        run: super::cmd_pre,
    },
    Command {
        group: "insert",
        name: "Horizontal rule",
        hint: "",
        run: super::cmd_hr,
    },
    Command {
        group: "insert",
        name: "Table…",
        hint: "",
        run: super::cmd_table,
    },
    Command {
        group: "table",
        name: "Add row after",
        hint: "",
        run: super::cmd_table_row,
    },
    Command {
        group: "table",
        name: "Add column after",
        hint: "",
        run: super::cmd_table_col,
    },
    Command {
        group: "insert",
        name: "Link…",
        hint: "",
        run: super::cmd_link,
    },
    Command {
        group: "insert",
        name: "Image from URL…",
        hint: "",
        run: super::cmd_image_url,
    },
    Command {
        group: "insert",
        name: "Special character…",
        hint: "",
        run: super::cmd_special_char,
    },
    // View
    Command {
        group: "view",
        name: "Outline (jump to heading)…",
        hint: "",
        run: super::cmd_outline,
    },
    Command {
        group: "view",
        name: "Help / shortcuts",
        hint: "Ctrl+/",
        run: super::cmd_help,
    },
    // Theme
    Command {
        group: "theme",
        name: "Theme: Light",
        hint: "",
        run: super::cmd_theme_light,
    },
    Command {
        group: "theme",
        name: "Theme: Dark",
        hint: "",
        run: super::cmd_theme_dark,
    },
    Command {
        group: "theme",
        name: "Theme: Sepia",
        hint: "",
        run: super::cmd_theme_sepia,
    },
    // Style
    Command {
        group: "style",
        name: "Font size…",
        hint: "",
        run: super::cmd_font_size,
    },
    Command {
        group: "style",
        name: "Line height…",
        hint: "",
        run: super::cmd_line_height,
    },
    Command {
        group: "style",
        name: "Max width…",
        hint: "",
        run: super::cmd_max_width,
    },
    Command {
        group: "style",
        name: "Page margin…",
        hint: "",
        run: super::cmd_page_margin,
    },
    Command {
        group: "style",
        name: "Font family…",
        hint: "",
        run: super::cmd_font_family,
    },
    Command {
        group: "style",
        name: "Accent color…",
        hint: "",
        run: super::cmd_accent,
    },
    Command {
        group: "style",
        name: "Reset all styles",
        hint: "",
        run: super::cmd_reset_styles,
    },
    // Block transforms (convert the block at the caret)
    Command {
        group: "block",
        name: "Convert block → Paragraph",
        hint: "",
        run: super::cmd_to_p,
    },
    Command {
        group: "block",
        name: "Convert block → Heading 1",
        hint: "",
        run: super::cmd_to_h1,
    },
    Command {
        group: "block",
        name: "Convert block → Heading 2",
        hint: "",
        run: super::cmd_to_h2,
    },
    Command {
        group: "block",
        name: "Convert block → Heading 3",
        hint: "",
        run: super::cmd_to_h3,
    },
    Command {
        group: "block",
        name: "Convert block → Heading 4",
        hint: "",
        run: super::cmd_to_h4,
    },
    Command {
        group: "block",
        name: "Convert block → Blockquote",
        hint: "",
        run: super::cmd_to_blockquote,
    },
    Command {
        group: "block",
        name: "Convert block → Bullet item",
        hint: "",
        run: super::cmd_to_bullet,
    },
    Command {
        group: "block",
        name: "Convert block → Numbered item",
        hint: "",
        run: super::cmd_to_numbered,
    },
    Command {
        group: "block",
        name: "Convert block → Preformatted",
        hint: "",
        run: super::cmd_to_pre,
    },
];

pub const TAG_CATALOG: &[(&str, &str)] = &[
    ("h1", "Heading 1"),
    ("h2", "Heading 2"),
    ("h3", "Heading 3"),
    ("h4", "Heading 4"),
    ("h5", "Heading 5"),
    ("h6", "Heading 6"),
    ("p", "Paragraph"),
    ("blockquote", "Blockquote"),
    ("ul", "Bullet list item"),
    ("ol", "Numbered list item"),
    ("pre", "Preformatted"),
    ("table", "Table"),
    ("tr", "Table row"),
    ("td", "Table cell"),
    ("th", "Table header cell"),
    ("hr", "Horizontal rule"),
    ("a", "Link"),
    ("img", "Image"),
    ("strong", "Bold"),
    ("em", "Italic"),
    ("u", "Underline"),
    ("s", "Strikethrough"),
    ("code", "Inline code"),
];

pub const SPECIAL_CHARS: &[(&str, char)] = &[
    ("em dash", '—'),
    ("en dash", '–'),
    ("ellipsis", '…'),
    ("left double quote", '\u{201C}'),
    ("right double quote", '\u{201D}'),
    ("left single quote", '\u{2018}'),
    ("right single quote", '\u{2019}'),
    ("bullet", '•'),
    ("middle dot", '·'),
    ("section sign", '§'),
    ("paragraph sign", '¶'),
    ("dagger", '†'),
    ("double dagger", '‡'),
    ("copyright", '©'),
    ("registered", '®'),
    ("trademark", '™'),
    ("degree", '°'),
    ("plus-minus", '±'),
    ("multiplication", '×'),
    ("division", '÷'),
    ("not equal", '≠'),
    ("less or equal", '≤'),
    ("greater or equal", '≥'),
    ("right arrow", '→'),
    ("left arrow", '←'),
    ("up arrow", '↑'),
    ("down arrow", '↓'),
    ("double right arrow", '⇒'),
    ("check mark", '✓'),
    ("cross mark", '✗'),
    ("pi", 'π'),
    ("lambda", 'λ'),
    ("sigma", 'Σ'),
    ("delta", 'Δ'),
    ("mu", 'μ'),
    ("non-breaking space", '\u{00A0}'),
];
