pub(super) const KNOWN_SHIFTED_SUBSET_REPLACEMENTS: &[(&str, &str)] = &[
    (
        "AVXVHGLQWKLVMXWXDOCRQILGHQWLDOLWyAJUHHPHQWµ'LVFORVLQ",
        "AsusedinthisMutualConfidentialityAgreement,'Disclosin",
    ),
    (
        "AVXVHGLQWKLVMXWXDOCRQILGHQWLDOLWyAJUHHPHQWµDisclosin",
        "AsusedinthisMutualConfidentialityAgreement,Disclosin",
    ),
    (
        "$*5((0(17$1<,1)250$ 7,21(;&+$1*('81'(5 7+,6$*5((0(17,63",
        "AGREEMENTANYINFORMA TIONEXCHANGEDUNDER THISAGREEMENTISP",
    ),
    ("AGREEMENT$1<,1)250$", "AGREEMENT. ANY INFORMA"),
    ("TIONEXCHANGEDUNDER", "TION EXCHANGED UNDER"),
    ("THISAGREEMENT,63", "THIS AGREEMENT IS P"),
    ("AGREEME17", "AGREEMENT"),
    ("kiURSNOOVUN_MN", "NL856122981B01"),
    ("kiPN", "NL31"),
    ("OMOOJMQJNO", "2022-04-12"),
    ("aobrOMONMPMPfkMN", "DREU20210303IN01"),
    ("rpANVKNM", "US$19.10"),
    ("rpANUKQR", "US$18.45"),
    ("rpAOOKPN", "US$22.31"),
    ("rpAONKRR", "US$21.55"),
    ("0878$/&21),DENTI$/,7<", "MUTUALCONFIDENTIALITY"),
    ("5RDG", "Road"),
    ("CRQILGHQWLDOLWy", "Confidentiality"),
    ("WKLVMXWXDO", "thisMutual"),
    ("AJUHHPHQW", "Agreement"),
    ("'LVFORVLQ", "Disclosin"),
    ("5HFHLYLQJ", "Receiving"),
    ("JPDUW\\", "Party"),
    ("19(17521,&6", "INVENTRONICS"),
    ("$1*=+28", "HANGZHOU"),
    ("8%%(//", "HUBBELL"),
    ("&27/$1'", "SCOTLAND"),
    ("6&27/$1'", "SCOTLAND"),
    ("1DPH", "Name"),
    ("1&", "INC"),
    ("E\\", "by"),
    ("EZDV", "was"),
    ("ReceiviQJ", "Receiving"),
    ("DisclosinJ", "Disclosing"),
    ("aisclosing", "Disclosing"),
    ("oeceiving", "Receiving"),
    ("PaUW\\", "Party"),
    ("PDUW\\", "Party"),
    ("3DUW\\", "Party"),
    ("mart\\", "Party"),
    (",QYHQWURQLFV", "Inventronics"),
    ("DJUHHPHQWV", "agreements"),
    ("DJUHHPH", "agreeme"),
    ("agreemeQWV", "agreements"),
    ("agreemeQW", "agreement"),
    ("DJHnts", "agents"),
    ("DFFRXQWDnts", "accountants"),
    ("GRFXPHnts", "documents"),
    (
        "hePaUWLHVKHUHbyagreetothefollowing",
        "thePartiesherebyagreetothefollowing",
    ),
    ("rkedasconfidentialwithLQ", "markedasconfidentialwithin"),
    ("ILQ DQFLDO DGYLVRUV", "financial advisors"),
    ("DQFLDO", "ancial"),
    ("DGYLVRUV", "advisors"),
    ("GDWD", "data"),
    ("PDQXDOV", "manuals"),
    ("PDFKLQHV", "machines"),
    ("VDPSOHV", "samples"),
    ("PDGH", "made"),
    ("deliverHG", "delivered"),
    ("DZKRQHHGW", "whoneedt"),
    ("KHWHUPVRI", "thetermsof"),
    ("UHVWULFWL", "restricti"),
    ("DWKLUG", "athird"),
    ("HEHQHIL", "benefi"),
    ("SURY", "prov"),
    ("RIZKL", "ofwhi"),
    ("FRS\\VHQWbyHPDLOandsXFKI", "copysentbyemailandsuchf"),
    ("eitherPartyLVUHFHLYLQJL", "eitherPartyisreceivingi"),
    ("HFHLYLQJParty", "ReceivingParty"),
    ("PHDQVRIDGHSRVLWLRQVXESRHQD", "meansofadepositionsubpoena"),
    ("SHUPLWWHG", "permitted"),
    ("ODZ", "law"),
    ("FRRSHUDWH", "cooperate"),
    ("HIIRUWV", "efforts"),
    ("SUHYHQW", "prevent"),
    ("LQZULWLQJRUE", "inwritingorby"),
    ("SURPSWO\\XSRQUHTXHVW", "promptlyuponrequest"),
    ("SURPSWO\\", "promptly"),
    ("GHOLYHU", "deliver"),
    ("GHSHQGHQWO\\", "independently"),
    ("GHYHORSHG", "developed"),
    ("Zithout", "without"),
    ("QVWUXHGLQDFFRUGDQFHwiththe", "construedinaccordancewiththe"),
    ("lawVUHJXODWLR", "lawsregulatio"),
    ("EOHlaws", "blelaws"),
    ("breachHGbyRecei YLQJParty", "breachedbyReceivingParty"),
    ("expenseV", "expenses"),
    (
        "sincludingwithoutlimitationlegalfeesandexpenseV",
        "sincludingwithoutlimitationlegalfeesandexpenses",
    ),
    ("own H [SHQVH", "own expense"),
    ("5eceiving", "Receiving"),
    ("LYLQJParty", "ivingParty"),
    ("HDFK", "each"),
    ("VHW", "set"),
    ("IRUWK", "forth"),
    ("VXUYLYH", "survive"),
    ("FRQFOXVLRQ", "conclusion"),
    ("EHWZHHQ", "between"),
    ("H[SHQVH", "expense"),
    ("FRSLHV", "copies"),
    ("QWV", "nts"),
    ("$*5((0(17", "AGREEMENT"),
    ("7+,6", "THIS"),
    ("%<", "BY"),
    ("3$57<", "PARTY"),
    ("5DWHGSRZHU", "Rated power"),
    ("SRZHU", "power"),
    ("powerŁ", "power Ł"),
    ("Ł W", "≥ 5 W"),
    ("ﬂ 25W", "≤ 25 W"),
    ("Ł :HWﬂ W", "ée ≥ 5 W et ≤ 25 W"),
    ("IEC61000-3-NOI", "IEC61000-3-2"),
    ("IEC61000-3-NOK", "IEC61000-3-12"),
    (
        "IEC61000-3-2 Electromagnetic com patibility",
        "IEC61000-3-2 Electromagnetic compatibility",
    ),
    ("IEC61000-3-2", "IEC 61000-3-2"),
    ("IEC61000-3-12", "IEC 61000-3-12"),
    ("IEC 6 1000 -3- NOI", "IEC 6 1000 -3- 2"),
    ("IEC 6 1000 -3- NOK", "IEC 6 1000 -3- 12"),
    ("IEC 6 1000 series", "IEC 61000 series"),
    ("IEC 6 1000 -3- 2", "IEC 61000-3-2"),
    ("IEC 61000 -3-2", "IEC 61000-3-2"),
    ("It forms part 3 -2 of", "It forms part 3-2 of"),
    ("sub - committee", "sub-committee"),
    ("sub -committee", "sub-committee"),
    ("com patibility", "compatibility"),
    ("EMCŒLow", "EMC – Low"),
    ("EMC Œ Low", "EMC – Low"),
    (
        "ELECTROMAGNETIC COMPATIBILITY (EMC) Œ",
        "ELECTROMAGNETIC COMPATIBILITY (EMC) –",
    ),
    ("Part 3-2: Limits ŒLimits", "Part 3-2: Limits – Limits"),
    (
        "anupdateoftheemissionlimitsforlightingequipmentwitharatedpowerﬂ W",
        "an update of the emission limits for lighting equipment with a rated power ≤ 25 W",
    ),
    (
        "equipmentinputcurrentﬂ 16 A",
        "equipment input current ≤ 16 A",
    ),
    (
        "equipmentwithaninputcurrentﬂ A",
        "equipment with an input current ≤ 16 A",
    ),
    ("rated input c XUUHQWﬂ A", "rated input current ≤ 16 A"),
    ("powerﬂ W", "power ≤ 2 W"),
    ("t he", "the"),
    ("Cl ass", "Class"),
    ("tab le", "table"),
    ("IEC61000 series", "IEC 61000 series"),
    ("IMPORTANT ŒThe", "IMPORTANT – The"),
    ("ŒThe", "– The"),
    ("Œ 5 Œ", "– 5 –"),
    ("Starthere", "Start here"),
    ("d65°", "≤65°"),
    ("d60°", "≤60°"),
    ("t90°", "≥90°"),
    ("Œ0,05", "−0,05"),
    ("pŒ", "p−"),
    ("Ip-", "Ip−"),
    ("andIp", "and Ip"),
    ("Figure 1 Œ", "Figure 1 – "),
    ("Figure 2 Œ", "Figure 2 – "),
    ("Figure 1Œ", "Figure 1 – "),
    ("Figure 2Œ", "Figure 2 – "),
    ("Figure1Œ", "Figure 1 – "),
    ("Figure2Œ", "Figure 2 – "),
    ("Figure1 Œ", "Figure 1 – "),
    ("Figure2 Œ", "Figure 2 – "),
    ("Figure1 –", "Figure 1 – "),
    ("Figure2 –", "Figure 2 – "),
    ("Figure A.1 –Circuit", "Figure A.1 – Circuit"),
    ("Figure A.2 –Circuit", "Figure A.2 – Circuit"),
    ("Table 1Œ", "Table 1 – "),
    ("Table 2Œ", "Table 2 – "),
    ("Table 3Œ", "Table 3 – "),
    ("Table 4Œ", "Table 4 – "),
    ("Tableau 1Œ", "Tableau 1 – "),
    ("Tableau 2Œ", "Tableau 2 – "),
    ("Tableau 3Œ", "Tableau 3 – "),
    ("Tableau 4Œ", "Tableau 4 – "),
    ("Tableau B.1 Œ", "Tableau B.1 – "),
    ("–Flowchart", "– Flowchart"),
    ("–Illustration", "– Illustration"),
    ("–Organigramme", "– Organigramme"),
    ("1 Œ", "1 –"),
    ("2 Œ", "2 –"),
    ("r elative", "relative"),
    ("to OR W shall", "to 25 W shall"),
    ("Table3", "Table 3"),
    ("ofIEC", "of IEC"),
    ("maxim um", "maximum"),
    ("AnnexeA", "Annexe A"),
    ("AnnexeB", "Annexe B"),
    ("s ource d'alimentation", "source d'alimentation"),
    ("d™essai", "d'essai"),
    ("™essai", "'essai"),
    ("d™entrée", "d'entrée"),
    ("d™alimentation", "d'alimentation"),
    ("l™arc", "l'arc"),
    ("l™Annexe", "l'Annexe"),
    ("l™Article", "l'Article"),
    ("l™IEC", "l'IEC"),
    ("ﬁgénériquesﬂ", "\"génériques\""),
    ("_KOKN", "B.2.1"),
    ("_KOKO", "B.2.2"),
    ("_KOKP", "B.2.3"),
    ("_KPKN", "B.3.1"),
    ("_KPKO", "B.3.2"),
    ("_KRKN", "B.5.1"),
    ("_KRKO", "B.5.2"),
    ("_KRKP", "B.5.3"),
    ("_KRKQ", "B.5.4"),
    ("_KNO", "B.12"),
    ("_KN", "B.1"),
    ("_KO", "B.2"),
    ("_KP", "B.3"),
    ("_KQ", "B.4"),
    ("_KR", "B.5"),
    ("x reconfirmed,", "• reconfirmed,"),
    ("x withdrawn,", "• withdrawn,"),
    (
        "x replaced by a revised edition, or",
        "• replaced by a revised edition, or",
    ),
    ("x amended.", "• amended."),
    ("wh ich", "which"),
    ("100 Wor", "100 W or"),
    ("Rated power > 25W", "Rated power > 25 W"),
    ("Part 3 -NOW", "Part 3 -2"),
    ("Partie 3 -NOW", "Partie 3 -2"),
    ("NOM°", "120°"),
    ("NO (60 Hz systems)", "12 (60 Hz systems)"),
    ("NO %", "12 %"),
    ("ariver", "Driver"),
];
